### ISSUE TITLE
Beginner guide

### ISSUE THREAD

**Issue by dpriver** [LibreLabUCM/teleg-api-bot#1]
Hi, i'd like to participate but i'm not used to web services... (web things in general), can someone write a short beginner guide?

No need for a extense step-by-step, just some references to relevant documentation.

**Comment by Akronix** [comment]
@Kuronogard hahah ha puesto un gusano el bot. es pinto que ha puesto un issue en el repo

**Comment by ergl** [comment]
I'll see if I can write up some guide for interacting with the Telegram API, although maybe @DevPGSV would prefer to do this himself?

**Comment by dpriver** [comment]
now I have been reading about this sort of things and can make a short guide if needed, but yours, @ergl seems pretty nice.
If you add it here, we can close the issue.

**Comment by ergl** [comment]
I went ahead and moved my guide over to a [Getting Started](https://github.com/LibreLabUCM/teleg-api-bot/wiki/Getting-started-with-the-Telegram-Bot-API) page in the wiki.

I also added a link to it in the Readme with c2105297 - feel free to close this issue.

**Comment by dpriver** [comment]
Perfect.
