### ISSUE TITLE
api_url config string

### ISSUE THREAD

**Issue by pblocz** [LibreLabUCM/teleg-api-bot#14]
change in config.yml api_url from the format "https://api.telegram.org/bot{token}/{method}"
to a more pythonic way using formatting string, for example `https://api.telegram.org/bot%(token)s/%(method)s`

**Comment by dpriver** [comment]
Since python 3.0, there is a new system to format strings 
https://www.python.org/dev/peps/pep-3101/

Done. 3ef6ce6bc80e7aef266f76bc3a29fcc8936d81aa
