### ISSUE TITLE
Crash on processing emojii

### ISSUE THREAD

**Issue by canihavesomecoffee** [LibreLabUCM/teleg-api-bot#23]
Hello,

I'm playing around with creating my own telegram bot, and I've noticed that if I send emojii's, the logger makes the bot crash due to a UnicodeEncodeError. This happens both when I send a emojii with the bot, as well as receiving one. 

This are the stacktraces:

```
Traceback (most recent call last):
...
  File "E:\telegram-bot\telegapi\telegbot.py", line 151, in __run_event
    self.on_receive_message(event)
  File "E:/telegram-bot/canihavesomecoffee.py", line 16, in receive_message
    logger.msg(msg)
  File "E:\telegram-bot\telegapi\logger.py", line 87, in msg
    self.log(self.info, output)
  File "E:\telegram-bot\telegapi\logger.py", line 57, in log
    print(print_text)
  File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f621' in position 167: character maps to <undefined>
```

When receiving a message, it's the same endpoint (also line 57 in logger.py)

On linux, the same occurs, but with a slightly different error message:

```
File "/home/telegram-bot/telegapi/logger.py", line 87, in msg
    self.log(self.info, output)
  File "/home/telegram-bot/telegapi/logger.py", line 57, in log
    print(print_text)
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f621' in position 112: ordinal not in range(128)
```

How to reproduce: Use the sample from the readme, and send the bot an emojii.

**Comment by ergl** [comment]
Hmm, can't seem to reproduce this on OSX, haven't had the time to test it on Windows / Linux though.

~~Seems like the Readme's code snippet is quite old, I have opened a PR that updates it (#25). Would you mind testing it with that new code and see if it still crashes?~~

EDIT: PR has been merged, mind trying with the latest version of the repo instead?

**Comment by canihavesomecoffee** [comment]
My guess is (if you cannot reproduce it on OSX), is that it might be because OSX supports the emoji out of the box, and as such can display them?

I've tested it with the latest  code (ab181e060035b39ab9e06e9758ac636bce551f22), and it is still throwing in the same errors. I had solved it by wrapping that line in a try-except method as quick work-around:

```
        print(print_text)
```

to

```
        try:
            print(print_text)
        except UnicodeEncodeError:
            print("Could not encode, contains unprintable characters")
```

**Comment by ergl** [comment]
You're right, I was able to crash it on Ubuntu 14.04.

The `try except` works, but I'm looking if I can fix this in a cleaner way

**Comment by canihavesomecoffee** [comment]
Good to know that it's confirmed :)

Yeah, I was aware that the try-except is a bit dirty, but was/is good enough to keep the bot running for now ^^

**Comment by ergl** [comment]
Should be fixed now, thanks for letting us know!
