### ISSUE TITLE
Problems with urllib

### ISSUE THREAD

**Issue by dpriver** [LibreLabUCM/teleg-api-bot#3]
For example, program breaks when trying to start a bot with an incorrect token. Also, some of the functions from urllib are deprecated and urlib2 homologous should be used instead.

After reading some information, i recommend to use the higher-level library [Requests](http://requests.readthedocs.org/en/latest/)

**Comment by pblocz** [comment]
I would also recommend switching to requests, since it is simpler for our use cases. [Here](http://stackoverflow.com/questions/2018026/should-i-use-urllib-or-urllib2-or-requests) are explained some of its advantages.

**Comment by ergl** [comment]
I added a specific issue for that on #8
