### ISSUE TITLE
python 2 or python 3?

### ISSUE THREAD

**Issue by pblocz** [LibreLabUCM/teleg-api-bot#4]
Which python version is the bot expected to work with? Since it uses python 3 specific `urllib.request`, it won't work with python 2.

**Comment by dpriver** [comment]
I faced that yesterday trying to make it work on my computer.
Exactly, you'll have to use python3.

We should make a dependency section in README or something.

I almost forget, here #3 I propose to switch to [Requests](http://docs.python-requests.org/en/latest/) ,which i think, can be compatible with python2, i haven't tested yet.

**Comment by ergl** [comment]
In my opinion, we should work with Python 3 - but switching to Requests is a good idea, haven't tested it yet though
