### ISSUE TITLE
Message type mutually exclusive

### ISSUE THREAD

**Issue by dpriver** [LibreLabUCM/teleg-api-bot#5]
Is someone sure that all optional _message_ fields are mutually exclusive?
It's relevant to whether or not use nested _"elifs"_ in **runevent()**

**Comment by ergl** [comment]
The API docs don't specify this, but they probably are - I can't see how you could send a different kinds of media in the same message.

That being said, we should probably expect that they are not mutually exclusive just in case

**Comment by dpriver** [comment]
It's true that multiple option message feels awkward thinking from a client side, but seems totally plausible from a bot.

Done cb587efd5497d3fe3089454c4f8c6be9788ef20d
