### ISSUE TITLE
bot's update check

### ISSUE THREAD

**Issue by dpriver** [LibreLabUCM/teleg-api-bot#6]
Actually, we check for updates by constant polling, it should be convenient to think in another mechanism, maybe a delayed polling if Telegram API doesn't provide event functionality.

**Comment by ergl** [comment]
The API does provide a web hook option, but you have to send it an https url so that Telegram can notify you.

This means that the bot has to be hosted on a public server, and to support HTTPS. For normal, local use, long polling is the best way to do this.

**Comment by ergl** [comment]
Having said that, adding an option to change the time elapsed between API requests can be a good idea - and add an exponential backoff if the API responds with an empty Update queue

**Comment by dpriver** [comment]
Ok, i think that the best solution could be to implement a new run() method that take advantage of the API hook capabilities, and modify the current one to poll in that efficient way.

**Comment by ergl** [comment]
I don't think we can add the web hook without testing it first - but I think @DevPGSV has a spare server to do so

**Comment by dpriver** [comment]
ops, i didn't know what long poll was about, with that in mind, there is no need for delay between getUpdates calls.
What we need is to implement that exponential backoff in case of connection failure.

**Comment by ergl** [comment]
Ok, I opened a specific issue for that on #7
